language: node_js

node_js:
  - "8.12"

script:
  - yarn truffle version
  - yarn lint
  - yarn truffle compile
  - yarn test
  - yarn solidity-coverage
  - cat coverage/lcov.info | coveralls
  - git status
